# Generated by Django 2.1.2 on 2019-01-21 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_Question_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='用户答案')),
                ('answer_is_true', models.BooleanField(default=True, verbose_name='答案是否正确')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '选择题历史记录表',
                'verbose_name_plural': '选择题历史记录表',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Completion_Question_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='用户答案')),
                ('answer_is_true', models.BooleanField(default=True, verbose_name='答案是否正确')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '填空题历史记录表',
                'verbose_name_plural': '填空题历史记录表',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='购买时间')),
                ('apply_bill', models.BooleanField(default=False, verbose_name='是否已经申请了发票')),
                ('is_draw_bill', models.BooleanField(default=False, verbose_name='是否已经开了发票')),
                ('taitou_type', models.IntegerField(default=1, verbose_name='发票类型,1:个人，2：公司')),
                ('taitou_text', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='抬头')),
                ('recognition_id', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='纳税人识别号')),
                ('email', models.EmailField(blank=True, default='', max_length=256, null=True, verbose_name='收件电子邮箱')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('invoice_date', models.DateTimeField(auto_now=True, verbose_name='申请发票时间')),
            ],
            options={
                'verbose_name': 'o订单',
                'verbose_name_plural': 'o订单',
                'ordering': ['-register_date'],
            },
        ),
        migrations.CreateModel(
            name='Outside_Reading_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='用户答案')),
                ('answer_is_true', models.BooleanField(default=True, verbose_name='答案是否正确')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课外阅读题目历史记录表',
                'verbose_name_plural': '课外阅读题目历史记录表',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Reading_Comprehension_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='用户答案')),
                ('answer_is_true', models.BooleanField(default=True, verbose_name='答案是否正确')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('reading_comprehension', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.reading_comprehension', verbose_name='阅读理解题目')),
            ],
            options={
                'verbose_name': '阅读理解题目历史记录表',
                'verbose_name_plural': '阅读理解题目历史记录表',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='GradeCourseOrder',
            fields=[
                ('orderbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usercourse.OrderBase')),
            ],
            options={
                'verbose_name': '课程学科订单',
                'verbose_name_plural': '课程学科订单',
                'ordering': ['-grade_course'],
            },
            bases=('usercourse.orderbase',),
        ),
    ]
