# Generated by Django 2.1.2 on 2019-01-14 08:11

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choice_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50, verbose_name='题目描述')),
                ('name', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='题目')),
                ('choice_type', models.CharField(choices=[('S', '单选'), ('M', '多选')], max_length=2)),
                ('choice_A', models.CharField(max_length=300, verbose_name='题目选项A')),
                ('choice_B', models.CharField(max_length=300, verbose_name='题目选项B')),
                ('choice_C', models.CharField(blank=True, max_length=300, null=True, verbose_name='题目选项C')),
                ('choice_D', models.CharField(blank=True, max_length=300, null=True, verbose_name='题目选项D')),
                ('answer', models.CharField(max_length=300, verbose_name='题目答案')),
                ('keypoint', models.CharField(blank=True, max_length=300, null=True, verbose_name='知识点')),
                ('point', models.IntegerField(blank=True, default=0, null=True, verbose_name='题目分值')),
                ('complexity', models.CharField(blank=True, max_length=300, null=True, verbose_name='难度')),
                ('show_time', models.CharField(max_length=10, verbose_name='题目出现时间填写(月-日的形式：如12-18)')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='试题解析')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
            ],
            options={
                'verbose_name': '选择题库',
                'verbose_name_plural': '选择题库',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='completion_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50, verbose_name='题目描述')),
                ('name', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='题目')),
                ('answer_1', models.CharField(max_length=300, verbose_name='填空答案1')),
                ('answer_2', models.CharField(blank=True, max_length=300, null=True, verbose_name='填空答案2')),
                ('answer_3', models.CharField(blank=True, max_length=300, null=True, verbose_name='填空答案3')),
                ('answer_4', models.CharField(blank=True, max_length=300, null=True, verbose_name='填空答案4')),
                ('answer_5', models.CharField(blank=True, max_length=300, null=True, verbose_name='填空答案5')),
                ('keypoint', models.CharField(blank=True, max_length=300, null=True, verbose_name='知识点')),
                ('point', models.IntegerField(blank=True, default=0, verbose_name='题目分值')),
                ('complexity', models.CharField(blank=True, max_length=300, null=True, verbose_name='难度')),
                ('show_time', models.CharField(max_length=10, verbose_name='题目出现时间填写(月-日的形式：如12-18)')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='试题解析')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
            ],
            options={
                'verbose_name': '填空题库',
                'verbose_name_plural': '填空题库',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='年级')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='grade_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('grade_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.grade', verbose_name='年级')),
            ],
            options={
                'verbose_name': '年级学科学费',
                'verbose_name_plural': '年级学科学费',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='outside_reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50, verbose_name='题目描述')),
                ('name', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='课外阅读')),
                ('keypoint', models.CharField(blank=True, max_length=300, null=True, verbose_name='知识点')),
                ('point', models.IntegerField(blank=True, default=0, verbose_name='题目分值')),
                ('complexity', models.CharField(blank=True, max_length=300, null=True, verbose_name='难度')),
                ('show_time', models.CharField(max_length=10, verbose_name='题目出现时间填写(12-18)')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='试题解析')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('questions_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.grade_course', verbose_name='题目分类')),
            ],
            options={
                'verbose_name': '课外阅读',
                'verbose_name_plural': '课外阅读',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='reading_comprehension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50, verbose_name='题目描述')),
                ('name', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='题目')),
                ('question_1', models.CharField(max_length=300, verbose_name='问题1')),
                ('answer_1', models.CharField(max_length=300, verbose_name='答案1')),
                ('question_2', models.CharField(blank=True, max_length=300, null=True, verbose_name='问题2')),
                ('answer_2', models.CharField(blank=True, max_length=300, null=True, verbose_name='答案2')),
                ('question_3', models.CharField(blank=True, max_length=300, null=True, verbose_name='问题3')),
                ('answer_3', models.CharField(blank=True, max_length=300, null=True, verbose_name='答案3')),
                ('question_4', models.CharField(blank=True, max_length=300, null=True, verbose_name='问题4')),
                ('answer_4', models.CharField(blank=True, max_length=300, null=True, verbose_name='答案4')),
                ('question_5', models.CharField(blank=True, max_length=300, null=True, verbose_name='问题5')),
                ('answer_5', models.CharField(blank=True, max_length=300, null=True, verbose_name='答案5')),
                ('keypoint', models.CharField(blank=True, max_length=300, null=True, verbose_name='知识点')),
                ('point', models.IntegerField(blank=True, default=0, null=True, verbose_name='题目分值')),
                ('complexity', models.CharField(blank=True, max_length=300, null=True, verbose_name='难度')),
                ('show_time', models.CharField(max_length=10, verbose_name='题目出现时间填写(月-日的形式：如12-18)')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='试题解析')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('questions_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.grade_course', verbose_name='题目分类')),
            ],
            options={
                'verbose_name': '阅读理解题库',
                'verbose_name_plural': '阅读理解题库',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学科')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='grade_course',
            name='subject_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='学科'),
        ),
        migrations.AddField(
            model_name='completion_question',
            name='questions_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.grade_course', verbose_name='题目分类'),
        ),
        migrations.AddField(
            model_name='choice_question',
            name='questions_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.grade_course', verbose_name='题目分类'),
        ),
        migrations.AlterUniqueTogether(
            name='grade_course',
            unique_together={('grade_name', 'subject_name')},
        ),
    ]
