# Generated by Django 2.1.2 on 2019-01-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outside_reading',
            name='show_time',
            field=models.DateField(verbose_name='题目出现时间填写(12-18)'),
        ),
    ]
