# Generated by Django 2.1.2 on 2019-01-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190116_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion_question',
            name='show_time',
            field=models.DateField(max_length=10, verbose_name='题目出现时间(月-日的形式：如12-18)'),
        ),
    ]
